before_script:
    # By default, we get an older version of libstdc++6 so we need to update it
    # http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install libstdc++6
    # Fake the ANDROID_HOME env var
    - mkdir android
    - ANDROID_HOME=android && export ANDROID_HOME
    - chmod +x install-cmake.sh

script:
    - "./install-cmake.sh"
    - "./android/cmake/3.6.3155560/bin/cmake --version"

sudo: required
